config/routes.rb
PizzaShop::Application.routes.draw do
  resources :pizzas

  resources :crusts

  resources :toppings

end

app/models/crust.rb
class Crust < ActiveRecord::Base
  attr_accessible :name
  has_many :pizzas
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  attr_accessible :crust_id, :name, :price, :topping_ids
  belongs_to :crust
  has_and_belongs_to_many :toppings
end

app/models/topping.rb
class Topping < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :pizzas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crusts }
    end
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
    @crust = Crust.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crust }
    end
  end

  # GET /crusts/new
  # GET /crusts/new.json
  def new
    @crust = Crust.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crust }
    end
  end

  # GET /crusts/1/edit
  def edit
    @crust = Crust.find(params[:id])
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(params[:crust])

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render json: @crust, status: :created, location: @crust }
      else
        format.html { render action: "new" }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crusts/1
  # PUT /crusts/1.json
  def update
    @crust = Crust.find(params[:id])

    respond_to do |format|
      if @crust.update_attributes(params[:crust])
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust = Crust.find(params[:id])
    @crust.destroy

    respond_to do |format|
      format.html { redirect_to crusts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pizzas }
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
    @pizza = Pizza.find(params[:id])
    @toppings = @pizza.toppings
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/new
  # GET /pizzas/new.json
  def new
    @pizza = Pizza.new
    @crusts = Crust.all
    @toppings = Topping.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/1/edit
  def edit
    @pizza = Pizza.find(params[:id])
    @crusts = Crust.all
    @toppings = Topping.all
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(params[:pizza])

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render json: @pizza, status: :created, location: @pizza }
      else
        format.html { render action: "new" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pizzas/1
  # PUT /pizzas/1.json
  def update
    params[:pizza][:topping_ids] ||= []
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      if @pizza.update_attributes(params[:pizza])
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy

    respond_to do |format|
      format.html { redirect_to pizzas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  # GET /toppings
  # GET /toppings.json
  def index
    @toppings = Topping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @toppings }
    end
  end

  # GET /toppings/1
  # GET /toppings/1.json
  def show
    @topping = Topping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topping }
    end
  end

  # GET /toppings/new
  # GET /toppings/new.json
  def new
    @topping = Topping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topping }
    end
  end

  # GET /toppings/1/edit
  def edit
    @topping = Topping.find(params[:id])
  end

  # POST /toppings
  # POST /toppings.json
  def create
    @topping = Topping.new(params[:topping])

    respond_to do |format|
      if @topping.save
        format.html { redirect_to @topping, notice: 'Topping was successfully created.' }
        format.json { render json: @topping, status: :created, location: @topping }
      else
        format.html { render action: "new" }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /toppings/1
  # PUT /toppings/1.json
  def update
    @topping = Topping.find(params[:id])

    respond_to do |format|
      if @topping.update_attributes(params[:topping])
        format.html { redirect_to @topping, notice: 'Topping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toppings/1
  # DELETE /toppings/1.json
  def destroy
    @topping = Topping.find(params[:id])
    @topping.destroy

    respond_to do |format|
      format.html { redirect_to toppings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/crusts/_form.html.erb
<%= form_for(@crust) do |f| %>
  <% if @crust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crust.errors.count, "error") %> prohibited this crust from being saved:</h2>

      <ul>
      <% @crust.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crusts/edit.html.erb
<h1>Editing crust</h1>

<%= render 'form' %>

<%= link_to 'Show', @crust %> |
<%= link_to 'Back', crusts_path %>

app/views/crusts/index.html.erb
<h1>Listing crusts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crusts.each do |crust| %>
  <tr>
    <td><%= crust.name %></td>
    <td><%= link_to 'Show', crust %></td>
    <td><%= link_to 'Edit', edit_crust_path(crust) %></td>
    <td><%= link_to 'Destroy', crust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crust', new_crust_path %>

app/views/crusts/new.html.erb
<h1>New crust</h1>

<%= render 'form' %>

<%= link_to 'Back', crusts_path %>

app/views/crusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @crust.name %>
</p>


<%= link_to 'Edit', edit_crust_path(@crust) %> |
<%= link_to 'Back', crusts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaShop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :crust_id %><br />
    <%= f.select :crust_id, @crusts.collect{ |c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <% for topping in @toppings %>
      <%= check_box_tag "pizza[topping_ids][]", topping.id, @pizza.toppings.include?(topping) %>
      <%= topping.name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<h1>Listing pizzas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Crust</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pizzas.each do |pizza| %>
  <tr>
    <td><%= pizza.name %></td>
    <td><%= pizza.price %></td>
    <td><%= pizza.crust_id %></td>
    <td><%= link_to 'Show', pizza %></td>
    <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
    <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pizza', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pizza.name %>
</p>

<p>
  <b>Price:</b>
  <%= @pizza.price %>
</p>

<p>
  <b>Crust:</b>
  <%= @pizza.crust.name %>
</p>
<p><b>Toppings:</b></p>
<ul>
<% for topping in @toppings %>
    <li><%= topping.name %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>

app/views/toppings/_form.html.erb
<%= form_for(@topping) do |f| %>
  <% if @topping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topping.errors.count, "error") %> prohibited this topping from being saved:</h2>

      <ul>
      <% @topping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toppings/edit.html.erb
<h1>Editing topping</h1>

<%= render 'form' %>

<%= link_to 'Show', @topping %> |
<%= link_to 'Back', toppings_path %>

app/views/toppings/index.html.erb
<h1>Listing toppings</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @toppings.each do |topping| %>
  <tr>
    <td><%= topping.name %></td>
    <td><%= link_to 'Show', topping %></td>
    <td><%= link_to 'Edit', edit_topping_path(topping) %></td>
    <td><%= link_to 'Destroy', topping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topping', new_topping_path %>

app/views/toppings/new.html.erb
<h1>New topping</h1>

<%= render 'form' %>

<%= link_to 'Back', toppings_path %>

app/views/toppings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @topping.name %>
</p>


<%= link_to 'Edit', edit_topping_path(@topping) %> |
<%= link_to 'Back', toppings_path %>